name: Node.js CI

on:
  push:
    branches: [ "pavana-website" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NEXT_PUBLIC_EMAIL: ${{secrets.NEXT_PUBLIC_EMAIL}}
      NEXT_PUBLIC_PASSWORD: ${{secrets.NEXT_PUBLIC_PASSWORD}}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Change directory
      run: cd /home/pavana/actions-runner/pavana/pavana/pavana
    - run: pm2 restart website
